#!/bin/bash

#checking os for Linux
uname

#verifying if os is Linux
if (( uname == "Linux")); then
	echo "uname is Linux"
if else (( uname != "Linux")); then
	echo "Error message: uname is not Linux" >> linuxsetup.log
	exit
fi

#making trash in ~
mkdir ~/.TRASH
#verifying for .vimrc and renaming it
if [ -f ~/.vimrc ]; then
	mv .vimrc .bup_vimrc
	echo "The current .vimrc file was renamed to .bup_vimrc" >> linuxsetup.log
else
	echo ".vimrc does not exist in the homedirectory"
fi
#putting the contents of etc/vimrc to .vimrc
etc/vimrc > ~/.vimrc

echo "source ∼/.dotfiles/etc/bashrc custom" >> ~/.bashrc
